import pymysql
# $McQ->registration_id = $request->input('registration_id');\
variableselectname = raw_input("Enter you variable select name example id=propductmcategory name=productmcategory")
loopvariable = raw_input("Enter you loopvariable name")
loopvariableid = raw_input("Enter you variable item (loop ex : product_id")
loopvariablename = raw_input("Enter you variable value (loop ex : product_name")
selectedvariable = raw_input("Enter you selectedid name")
person = raw_input("Enter you variable name (recordset")

print("")
print("")    
print("-------------------------------------------------------")
print('<div class="form-group col-md-12 " >')
print('		<label class="col-md-4 control-label" for="textinput">Kategori Produk *</label>')
print('	<div class="col-md-6">')
print('			<select class="form-control" id="' + variableselectname + '" name="' + variableselectname + '" style="width: 300px">')
print('                <option value="0">[PILIH]</option>')
print('				<?php ')
print('					if(isset($' + loopvariable + ')){')
print('						foreach($' + loopvariable + ' as $item){')
print('							?>')
print('						    	<option <? if(isset($' + selectedvariable + ') && $' + selectedvariable + ' == $item->' + loopvariableid + '){')
print('                                echo " selected ";')
print('							}?> value="<?php echo $' + loopvariableid + ';?>"><?php echo $item->' + loopvariablename + ';?></option><?php	')
print('						}')
print('				 	}')
print('				?>')
print('		   </select>')
print('		</div>')
print('	</div>')